### PR TITLE
[Chore] Add arm64 as valid arch when building for simulator on M1 macs

### PR DESCRIPTION
**Pull request by michaelknoch**
this pr allows building and linking `Down` when running on arm64 simulator

Error message without this:
```
Could not find module 'Down' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64
```

### CODE REVIEW

**Comment by michaelknoch** [comment]
@johnxnguyen

**Comment by johnxnguyen** [comment]
Hey @michaelknoch , thanks for the contribution! Do you know if a similar solution is needed when Down is pulled in via Swift Package Manager?

**Comment by michaelknoch** [comment]
I think exactly this change is needed when fetching Down via SPM for running an ios application on an arm64 simulator, but I haven't tried it. We are fetching Down as a git submodule and embedding it directly into the xcode project. I was wondering if it would make sense to get rid of the `VALID_ARCHS` variable entirely. Xcode should be able to set the `ARCHS` variable (which is basically the same) automatically. @johnxnguyen

**Comment by johnxnguyen** [comment]
> I was wondering if it would make sense to get rid of the `VALID_ARCHS` variable entirely. Xcode should be able to set the ARCHS variable (which is basically the same) automatically. 

@michaelknoch unfortunately I don't have an M1 laptop so can't really say what works or doesn't work. If this PR solves the issue for you, I'm happy to to approve it.

**Comment by michaelknoch** [comment]
It does definitely solve the build errors when building for an arm64 simulator on an M1 mac @johnxnguyen

**Review by johnxnguyen — APPROVED** [review]
Thanks again @michaelknoch

**Pull request merged**
